---
title: "Posts"
---

# COVID-19 Outbreak: A Wake-Up Call on Biodiversity Conservation in Nigeria
An African proverb rightly says, “If it happens that a vulture is hungry a catastrophe will occur in the town!” On 30 January 2020, the World Health Organisation (WHO) declared coronavirus 2019 (COVID-19), a Public Health Emergency of International Concern (PHEIC) with a [death toll](https://www.worldometers.info/coronavirus/) and socioeconomic and environmental impacts worldwide.


For ages, man has been the dominant creature on the planet earth. He domesticates wildlife for food, kills them for sport, commercializes them for pets, and persecutes them in the name of spiritual and unfounded beliefs. It is not surprising that the outbreak of many zoonotic diseases (diseases that jump from wildlife to humans, such as Ebola, HIV/AIDS, and SARS) including the recent Severe Acute Respiratory Syndrome (SARS – CoV-2), #COVID-19, is in a way related to wildlife trade and the #Anthropocene era we are witnessing (which is characterized by human dominance and induced impacts on the planet). How did this happen? Could it be that nature is fighting back amidst the Anthropocene, responding to human transgressions?...[read more](https://conservationbiolog2.wixsite.com/cncb/post/covid-19-outbreak-a-wake-up-call-on-biodiversity-conservation-in-nigeria)