---
title: "Publications/presentations"
urlcolor: blue
---


- Evaluation of Vegetation Characteristics and Habitat Utilization by Birds in some Airports in Nigeria (Unpublished master's thesis). *A. P. Leventis Ornithological Research Institute, University of Jos, Nigeria* <a href="MSc Defense ppt__Danmallam Bello Adamu.pdf#" class="fas fa-download" title="Download presentation as PDF">Download presentation</a>


- Ringim, A.S., Muhammad, S.I., Bako, L.A., Abubakar, H.M., Isa, S.M., Joseph, D.N., Aliyu, A.B., Bunu, A.S., Abdullahi, H.A., Jalo, M.I., Eveso, J.O., Mathew, E.D., **Danmallam, B.A.,** Mador, U., Paul, J.I., Aminu, I., Lawal, A.I., Ibrahim, J.I., & Ponyil, A.N. Arewa Atlas Team: report of a ve-day 100 pentads survey, with two out of range forms. Biodiversity Observation (in press)


- [Effects of Size and Bark Roughness of Parkia biglobosa on Lichen  Colonization: Implication for Conservation](https://doi.org/10.5455/sf.32286)


- [Presentation: A comparative Study of Tree Vegetation Composition between Fenced and Unfenced area of Sumu wildlife Park, Bauchi State. *The 6th Biennial Conference of Nigerian Tropical Biology Association (NTBA), Dutse, 2019.*](https://ntbaconf2018.wordpress.com/resources/)


- Presentation: Value Clarification Promotes a Healthier Future. *The 1st Regional Education Summit on HIV/AIDs in Africa (RESHAA) and Youth Speak out on Reproductive Health. Federal Ministry of Education Abuja, 2011*


<a href="mailto:adamubello001@gmail.com" class="ion-email" title="email"></a>  <a href="https://twitter.com/BelloDanmallam1?s=08" class="ion-social-twitter" title="twitter"></a>   <a href="https://github.com/bdanmallam" class="ion-social-github" title="GitHub"></a>  <a href="https://api.whatsapp.com/send?phone=2348038175878&text=Hi%20Bello" class="fa fa-whatsapp" title="WhatsApp"></a>

